# Generated by Django 5.1.6 on 2025-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
