# Generated by Django 5.1.6 on 2025-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedfile_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
