# Generated by Django 5.1.6 on 2025-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_client_name_product_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('delivered', 'Delivered')], default='on_time', max_length=20),
        ),
    ]
