# Generated by Django 5.1.6 on 2025-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
