# Generated by Django 5.1.6 on 2025-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadedfile_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschema',
            name='grist_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userschema',
            name='grist_doc_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschema',
            name='grist_view_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
