# Generated by Django 5.1.6 on 2025-06-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_onboardingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschema',
            name='grist_doc_id',
        ),
        migrations.RemoveField(
            model_name='userschema',
            name='grist_doc_url',
        ),
        migrations.RemoveField(
            model_name='userschema',
            name='grist_view_url',
        ),
    ]
