# Generated by Django 5.1.6 on 2025-06-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usertableschema_delete_userschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertableschema',
            name='db_table_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='primary_key',
            field=models.CharField(default='id', max_length=128),
        ),
    ]
