# Generated by Django 5.1.6 on 2025-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='User UI preferences like theme, font size, etc.'),
        ),
    ]
