# Generated by Django 5.1.6 on 2025-05-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(default='Free', max_length=20),
        ),
    ]
