# Generated by Django 5.1.6 on 2025-06-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_dashboard_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
