# Generated by Django 5.1.6 on 2025-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_last_dashboard_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_feedback_to_train_model',
            field=models.BooleanField(default=True),
        ),
    ]
