# Generated by Django 5.1.6 on 2025-07-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_id_alter_onboardingprogress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Platform Superuser)'), ('owner', 'Org Owner'), ('ceo', 'Full Access (CEO/Global)'), ('national_manager', 'National Manager'), ('regional_manager', 'Regional Manager'), ('local_manager', 'Site/Local Manager'), ('employee', 'Employee/Basic'), ('client', 'Client/Partner/3rd Party'), ('tech_support', 'Tech Support'), ('read_only', 'Read Only'), ('custom', 'Custom')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin (Platform Superuser)'), ('owner', 'Org Owner'), ('ceo', 'Full Access (CEO/Global)'), ('national_manager', 'National Manager'), ('regional_manager', 'Regional Manager'), ('local_manager', 'Site/Local Manager'), ('employee', 'Employee/Basic'), ('client', 'Client/Partner/3rd Party'), ('tech_support', 'Tech Support'), ('read_only', 'Read Only'), ('custom', 'Custom')], default='client', max_length=20)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.organization'),
        ),
    ]
