# Generated by Django 5.1.6 on 2025-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagrid', '0002_alter_usergridconfig_id_alter_usertablerow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergridconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertablerow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertableschema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
