# Generated by Django 5.1.6 on 2025-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('datagrid', '0003_alter_usergridconfig_id_alter_usertablerow_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertablerow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='usergridconfig',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usertableschema',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergridconfig',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this grid config belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_configs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='usertablerow',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this table row belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this table schema belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_schemas', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='usergridconfig',
            unique_together={('user', 'org', 'table_name')},
        ),
        migrations.AlterUniqueTogether(
            name='usertableschema',
            unique_together={('user', 'org', 'table_name')},
        ),
    ]
