# Generated by Django 5.1.6 on 2025-07-14 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_settings'),
        ('datagrid', '0004_alter_usertablerow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('file_id', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=512)),
                ('table_name', models.CharField(max_length=128)),
                ('client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('pipeline_version', models.CharField(choices=[('legacy', 'Legacy Pipeline'), ('enhanced', 'Enhanced Pipeline v2.0')], default='enhanced', max_length=20)),
                ('airflow_dag_id', models.CharField(blank=True, max_length=128, null=True)),
                ('airflow_run_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_records_processed', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('average_quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('quality_metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('processing_metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('quality', 'Data Quality Issue'), ('processing', 'Processing Failure'), ('performance', 'Performance Issue'), ('storage', 'Storage Issue'), ('security', 'Security Issue')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('table_name', models.CharField(blank=True, max_length=128, null=True)),
                ('composite_key', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_alerts', to='accounts.organization')),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='datagrid.dataingestionjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=128)),
                ('source_identifier', models.CharField(max_length=512)),
                ('destination_system', models.CharField(max_length=128)),
                ('destination_identifier', models.CharField(max_length=512)),
                ('transformation_type', models.CharField(choices=[('ingestion', 'Data Ingestion'), ('validation', 'Data Validation'), ('transformation', 'Data Transformation'), ('aggregation', 'Data Aggregation'), ('export', 'Data Export')], max_length=20)),
                ('transformation_description', models.TextField()),
                ('transformation_rules', models.JSONField(blank=True, default=dict)),
                ('composite_keys_affected', models.JSONField(blank=True, default=list)),
                ('records_affected', models.IntegerField(default=0)),
                ('transformation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineage_entries', to='datagrid.dataingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_lineage', to='accounts.organization')),
            ],
            options={
                'ordering': ['-transformation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128)),
                ('report_date', models.DateField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_records', models.IntegerField(default=0)),
                ('records_with_errors', models.IntegerField(default=0)),
                ('records_with_warnings', models.IntegerField(default=0)),
                ('overall_quality_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('validity_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('detailed_metrics', models.JSONField(blank=True, default=dict)),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='datagrid.dataingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='accounts.organization')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128)),
                ('composite_key', models.CharField(max_length=512)),
                ('version', models.IntegerField()),
                ('previous_version', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('MERGE', 'Merge')], max_length=10)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('data_hash', models.CharField(max_length=64)),
                ('previous_data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('change_timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=512, null=True)),
                ('validation_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='datagrid.dataingestionjob')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='accounts.organization')),
            ],
            options={
                'ordering': ['-change_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDataMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_date', models.DateField()),
                ('total_storage_bytes', models.BigIntegerField(default=0)),
                ('mongodb_storage_bytes', models.BigIntegerField(default=0)),
                ('postgresql_storage_bytes', models.BigIntegerField(default=0)),
                ('total_records', models.BigIntegerField(default=0)),
                ('active_records', models.BigIntegerField(default=0)),
                ('archived_records', models.BigIntegerField(default=0)),
                ('total_tables', models.IntegerField(default=0)),
                ('active_tables', models.IntegerField(default=0)),
                ('ingestion_jobs_count', models.IntegerField(default=0)),
                ('successful_jobs_count', models.IntegerField(default=0)),
                ('failed_jobs_count', models.IntegerField(default=0)),
                ('average_quality_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('records_with_quality_issues', models.BigIntegerField(default=0)),
                ('active_users_count', models.IntegerField(default=0)),
                ('total_user_actions', models.IntegerField(default=0)),
                ('average_ingestion_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_query_time_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detailed_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_metrics', to='accounts.organization')),
            ],
            options={
                'ordering': ['-metrics_date'],
            },
        ),
        migrations.AddIndex(
            model_name='dataingestionjob',
            index=models.Index(fields=['org', 'status'], name='datagrid_da_org_id_ef6ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='dataingestionjob',
            index=models.Index(fields=['org', 'table_name'], name='datagrid_da_org_id_2cbde4_idx'),
        ),
        migrations.AddIndex(
            model_name='dataingestionjob',
            index=models.Index(fields=['created_at'], name='datagrid_da_created_ea3bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataingestionjob',
            index=models.Index(fields=['initiated_by'], name='datagrid_da_initiat_f652ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dataalert',
            index=models.Index(fields=['org', 'status'], name='datagrid_da_org_id_46ebeb_idx'),
        ),
        migrations.AddIndex(
            model_name='dataalert',
            index=models.Index(fields=['severity', 'status'], name='datagrid_da_severit_5e397c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataalert',
            index=models.Index(fields=['alert_type'], name='datagrid_da_alert_t_a622ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dataalert',
            index=models.Index(fields=['created_at'], name='datagrid_da_created_aa9950_idx'),
        ),
        migrations.AddIndex(
            model_name='dataalert',
            index=models.Index(fields=['assigned_to'], name='datagrid_da_assigne_d0b53e_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['org', 'transformation_timestamp'], name='datagrid_da_org_id_3ff071_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['source_system', 'source_identifier'], name='datagrid_da_source__7e9fed_idx'),
        ),
        migrations.AddIndex(
            model_name='datalineage',
            index=models.Index(fields=['destination_system', 'destination_identifier'], name='datagrid_da_destina_384ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['org', 'table_name', 'report_date'], name='datagrid_da_org_id_b3c317_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['overall_quality_score'], name='datagrid_da_overall_9d151b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualityreport',
            index=models.Index(fields=['created_at'], name='datagrid_da_created_ccb8f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataqualityreport',
            unique_together={('org', 'table_name', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='dataversionhistory',
            index=models.Index(fields=['org', 'table_name', 'composite_key'], name='datagrid_da_org_id_fd562d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataversionhistory',
            index=models.Index(fields=['composite_key', 'version'], name='datagrid_da_composi_a0894e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataversionhistory',
            index=models.Index(fields=['change_timestamp'], name='datagrid_da_change__64f465_idx'),
        ),
        migrations.AddIndex(
            model_name='dataversionhistory',
            index=models.Index(fields=['changed_by'], name='datagrid_da_changed_665eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='dataversionhistory',
            index=models.Index(fields=['change_type'], name='datagrid_da_change__01cab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataversionhistory',
            unique_together={('org', 'table_name', 'composite_key', 'version')},
        ),
        migrations.AddIndex(
            model_name='organizationdatametrics',
            index=models.Index(fields=['org', 'metrics_date'], name='datagrid_or_org_id_2cb83b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationdatametrics',
            index=models.Index(fields=['metrics_date'], name='datagrid_or_metrics_aea65d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationdatametrics',
            index=models.Index(fields=['created_at'], name='datagrid_or_created_089a72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdatametrics',
            unique_together={('org', 'metrics_date')},
        ),
    ]
