# Generated by Django 5.1.6 on 2025-07-15 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_settings'),
        ('datagrid', '0005_dataingestionjob_dataalert_datalineage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertableschema',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Quick flag to identify shared schemas'),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When this schema was shared organization-wide', null=True),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='shared_by',
            field=models.ForeignKey(blank=True, help_text='User who shared this schema organization-wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='sharing_level',
            field=models.CharField(choices=[('personal', 'Personal (Private)'), ('organization', 'Organization-wide (Shared)')], default='personal', help_text='Determines who can access this schema', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usertableschema',
            index=models.Index(fields=['org', 'sharing_level'], name='datagrid_us_org_id_480c62_idx'),
        ),
        migrations.AddIndex(
            model_name='usertableschema',
            index=models.Index(fields=['org', 'is_shared'], name='datagrid_us_org_id_c367d4_idx'),
        ),
        migrations.AddIndex(
            model_name='usertableschema',
            index=models.Index(fields=['user', 'org', 'table_name'], name='datagrid_us_user_id_b545e5_idx'),
        ),
    ]
