# Generated by Django 5.1.6 on 2025-07-15 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_settings'),
        ('datagrid', '0006_usertableschema_is_shared_usertableschema_shared_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertableschema',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this version is the active one'),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usertableschema',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usertableschema',
            name='sharing_level',
            field=models.CharField(choices=[('private', 'Private'), ('org', 'Organization'), ('public', 'Public')], default='personal', help_text='Determines who can access this schema', max_length=20),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File'), ('reference', 'Reference')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of valid choices for this field')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('decimal_places', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('foreign_key_table', models.CharField(blank=True, max_length=128, null=True)),
                ('foreign_key_column', models.CharField(blank=True, max_length=128, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Column width in pixels', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_columns', to='datagrid.usertableschema')),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['schema', 'order'], name='datagrid_co_schema__f8bb2e_idx'), models.Index(fields=['is_primary_key'], name='datagrid_co_is_prim_afb8b9_idx'), models.Index(fields=['data_type'], name='datagrid_co_data_ty_05f538_idx')],
                'unique_together': {('schema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('shared', 'Shared'), ('unshared', 'Unshared'), ('version_created', 'Version Created'), ('column_added', 'Column Added'), ('column_updated', 'Column Updated'), ('column_deleted', 'Column Deleted'), ('column_reordered', 'Column Reordered')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(blank=True, max_length=128, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='datagrid.usertableschema')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['schema', '-timestamp'], name='datagrid_sc_schema__03a101_idx'), models.Index(fields=['action', '-timestamp'], name='datagrid_sc_action_dcce6c_idx'), models.Index(fields=['user', '-timestamp'], name='datagrid_sc_user_id_a6f37a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemaPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('admin', 'Admin')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='datagrid.usertableschema')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['schema', 'permission'], name='datagrid_sc_schema__15793d_idx'), models.Index(fields=['user', 'permission'], name='datagrid_sc_user_id_061224_idx'), models.Index(fields=['org', 'permission'], name='datagrid_sc_org_id_5f654d_idx')],
                'unique_together': {('schema', 'user', 'org')},
            },
        ),
    ]
