# Generated by Django 5.1.6 on 2025-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0004_alter_analyticsdashboard_id_alter_dashboardchart_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdashboard',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this dashboard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsdashboard',
            unique_together={('user', 'org', 'name')},
        ),
    ]
