# Generated by Django 5.1.6 on 2025-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analyticsdashboard_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardchart',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('table', 'Table'), ('area', 'Area'), ('scatter', 'Scatter'), ('radar', 'Radar'), ('composed', 'Composed')], max_length=32),
        ),
    ]
