# Generated by Django 5.1.6 on 2025-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aifeedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
