# Generated by Django 5.1.6 on 2025-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai', '0004_alter_aifeedback_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aifeedback',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this feedback belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
