# Generated by Django 5.1.6 on 2025-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_uploadedfile_id_alter_userfile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='client_name',
            new_name='client_id',
        ),
    ]
