# Generated by Django 5.1.6 on 2025-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_client_name_uploadedfile_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='org_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
