# Generated by Django 5.1.6 on 2025-07-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('files', '0006_remove_uploadedfile_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='client_name',
            field=models.CharField(default='', help_text='Legacy field for migration', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('user', 'org', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='userfile',
            unique_together={('user', 'org', 'object_key')},
        ),
    ]
